
def options(opt):
    opt.load(['compiler_cxx'])

def configure(conf):
    conf.load(['compiler_cxx'])

def build(bld):
    bld.program(
        features  = ['cxx', 'cxxprogram'],
        source    = bld.path.ant_glob('src/*.cpp'),
        target    = 'TicTacToe',
        cxxflags  = ['-g', '-O0', '-Wall', '-Werror', '-std=c++11'],
    )
